package cf.study.web.html;

import java.io.StringWriter;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.apache.html.dom.HTMLBuilder;
import org.apache.xml.serialize.HTMLSerializer;
import org.apache.xml.serialize.OutputFormat;
import org.junit.Test;
import org.w3c.dom.html.HTMLDocument;

public class HtmlTests {

	@Test
	public void testHtmlBuilder() {
		HTMLBuilder hb = new HTMLBuilder();

		try {
			hb.startDocument();
			hb.startElement("HTML", null);
			hb.startElement("HEAD", null);
			hb.startElement("TITLE", null);
			hb.characters("generated by HTMLBuilder");
			hb.endElement("TITLE");
			hb.endElement("HEAD");
			hb.startElement("BODY", null);
			hb.endElement("BODY");
			hb.endElement("HTML");

			final HTMLDocument hd = hb.getHTMLDocument();

			System.out.println(hd);

			StringWriter writer = new StringWriter();
			TransformerFactory tf = TransformerFactory.newInstance();
			// identity
			Transformer t = tf.newTransformer();
			t.setOutputProperty(OutputKeys.INDENT, "yes");
			t.transform(new DOMSource(hd), new StreamResult(writer));

			System.out.println(writer.toString());
			
			hb.endDocument();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static final String PAYPAL_ROOT_URL = "https://sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&";
	
	@Test
	public void testHtmlSerializer() {
		StringWriter writer = new StringWriter();
		final OutputFormat format = new OutputFormat();
		format.setIndent(4);
		format.setIndenting(true);
		HTMLSerializer hb = new HTMLSerializer(writer, format);

		try {
			hb.startDocument();
			hb.startElement("HTML", null);
			hb.startElement("HEAD", null);
			hb.startElement("TITLE", null);
			final String titleStr = "redirecting to paypal...";
			hb.characters(titleStr.toCharArray(), 0, titleStr.length());
			hb.endElement("TITLE");
			hb.endElement("HEAD");
			hb.startElement("BODY", null);
			hb.startElement("SCRIPT", null);
			
			final String scriptStr = "document.location.href=\"" + PAYPAL_ROOT_URL + "token" + "&guid=" + "guid" + "\"";
			hb.characters(scriptStr.toCharArray(), 0, scriptStr.length());
			
			hb.endElement("SCRIPT");
			hb.endElement("BODY");
			hb.endElement("HTML");

			hb.endDocument();
			
			System.out.println(writer);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
